project:
  type: book
  output-dir: public
  execute-dir: project

book:
  title: "Guides for the r-cubed courses"
  favicon: "images/favicon.ico"
  site-url: "https://guides.rostools.org"
  repo-url: "https://gitlab.com/rostools/guides"
  repo-branch: main
  repo-actions: [edit, issue, source]
  search:
    location: navbar
    type: overlay
  chapters:
    - index.md
    - part: "Instructors"
      chapters:
      - workshops.md
      - instructors.md
      - helpers.md
      - CONTRIBUTING.md
      - CODE_OF_CONDUCT.md
    - part: "Participants"
      chapters:
      - conduct.qmd
      - connect-github.qmd
      - posit-cloud.qmd
      - learning.qmd
      - faq.qmd
  page-footer:
    center:
      - text: "License"
        href: LICENSE.md

# bibliography: references.bib
callout-appearance: minimal
reference-location: margin
citation-location: margin
crossref:
  chapters: true

format:
  html:
    from: markdown+emoji
    code-link: true
    theme:
      - litera
      - includes/theme.scss
    include-before-body:
      - "includes/site-counter.html"
      - "includes/contribute.html"

editor_options:
  markdown:
    wrap: 72
    canonical: true

