project:
  type: r3-theme

book:
  title: "Guides for the r-cubed workshops"
  favicon: "images/favicon.ico"
  site-url: "https://guides.rostools.org"
  repo-url: "https://github.com/rostools/guides"
  chapters:
    - index.qmd
    - part: "Instructors"
      chapters:
      - workshops.qmd
      - instructors.qmd
      - helpers.qmd
      - CONTRIBUTING.md
      - CODE_OF_CONDUCT.md
    - part: "Participants"
      chapters:
      - conduct.qmd
      - connect-github.qmd
      - posit-cloud.qmd
      - learning.qmd
      - faq.qmd
    - LICENSE.md
  page-footer:
    center:
      - text: "License: CC BY 4.0 {{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}}"
        href: LICENSE.html

format:
  r3-theme-html:
    include-before-body:
      - "includes/site-counter.html"

editor:
  markdown:
    wrap: 72
    canonical: true

