project:
  type: r3-theme

book:
  title: "Guides for the r-cubed courses"
  favicon: "images/favicon.ico"
  site-url: "https://guides.rostools.org"
  repo-url: "https://github.com/rostools/guides"
  chapters:
    - index.qmd
    - part: "Instructors"
      chapters:
      - workshops.md
      - instructors.md
      - helpers.md
      - CONTRIBUTING.md
      - CODE_OF_CONDUCT.md
    - part: "Participants"
      chapters:
      - pre-course.qmd
      - conduct.qmd
      - connect-github.qmd
      - posit-cloud.qmd
      - learning.qmd
      - faq.qmd
  page-footer:
    center:
      - text: "License"
        href: LICENSE.html

format:
  r3-theme-html:
    include-before-body:
      - "includes/site-counter.html"
      - "includes/contribute.html"

editor:
  markdown:
    wrap: 72
    canonical: true

