# Frequently asked questions

## Installation Problems

::: {.callout-tip collapse="true"}
### What do I do if I don't have admin rights and can't install the newest versions of programs?

Depending on your institutional policies and infrastructure, you may not
be able to download newer versions of R and RStudio. Firstly, you should
contact your IT support person to see whether you are able to access an
updated version. While you could attempt to use the older version of
these programs available to you, you may notice that some things either
look quite different or not work at all. One solution is to use the
Posit Cloud platform, as per the instructions in the section [Setting up
Posit Cloud](#setting-up-rstudio-cloud).
:::

::: {.callout-tip collapse="true"}
### Why did my output have so much red text when I tried to install packages?

Rest assured that this is simply the way that R informs you that
packages are being installed, even though it may look scary. If there
really was an error, the output would likely begin with a message saying
"Error: ..." or "Warning: ...", to differentiate between informational
compared to error messages.
:::

::: {.callout-tip collapse="true"}
### I have an error about `pythonPath` when I start RStudio, can I fix it?

You can fix this problem by going to the menu "Tools \> Global options",
then going to the "Python" tab on the sidebar. There, if you untick the
"Automatically activate project-local Python environments" option, it
will stop giving you the error.
:::

::: {.callout-tip collapse="true"}
### Why did I receive a bunch of error messages when I tried to install packages?

For some Windows users, you may need to install
[Rtools](https://cran.r-project.org/index.html).
:::

::: {.callout-tip collapse="true"}
### Help! My code isn't working, even though I've followed all the instructions.

This is the most common problem you will face, check out the
[troubleshooting
section](https://r-cubed-intro.rostools.org/sessions/project-management.html#encountering-problems-and-finding-help)
in the Introductory course on how to solve problems.
:::

## Difficult to diagnose issues

::: {.callout-tip collapse="true"}
### Not sure why my R and Git aren't working well with my project... help!

There could be many issues here. One that we've encountered is that your
file path may have a non-standard/recognizable character in the file
path, like the Danish å or æ. Replacing these characters with the
"English standard" may solve this problem.
:::
