# Continued learning

## Free online books:

### Beginner

-   [R for Data Science](https://r4ds.hadley.nz): Excellent open and
    online resource for using R for data analysis and data science.
-   [Fundamentals of Data
    Visualization](https://serialmentor.com/dataviz/): Excellent online
    resource for using ggplot2 and R graphics. The book mostly focuses
    on concepts and theory of how to visualize, rather than the
    practicalities (i.e. no coding involved).
-   [ModernDive: Statistical Inference via Data
    Science](https://moderndive.com/): Great book on using statistics
    and data science methods in R.
-   [Happy Git and GitHub for the useR](https://happygitwithr.com/)
    (**highly recommended**): Specifically useful is the chapter on
    [Daily Workflows](https://happygitwithr.com/workflows-intro.html)
    using Git.
-   [Data Visualization: A practical
    introduction](https://socviz.co/index.html#preface): A book that
    goes into practical as well as conceptual detail on how and why to
    make certain graphs, given your data.
-   [Course material for a statistics class](https://stat545.com/):
    Excellent course material for teaching statistics and R.
-   [ModernDive: Statistical Inference via Data
    Science](https://moderndive.com/): Great book on using statistics
    and data science methods in R
-   [Data Skills for Reproducible
    Research](https://psyteachr.github.io/reprores-v3/): A book-format
    resource for learning about reproducible research practices, mainly
    aimed at psychology students.
-   [Data wrangling, exploration, and analysis with
    R](https://stat545.com/): A foundational course, originally designed
    by Jenny Bryan (of Posit and tidyverse) for students in the life
    sciences at UBC, but now used by students in many fields.

### Intermediate and above

-   [Efficient R
    Programming](https://csgillespie.github.io/efficientR/): Excellent
    book on being efficient when writing R code.
-   [Advanced R](https://adv-r.hadley.nz/): Detailed book on advanced
    features of R.
-   [R Packages](https://r-pkgs.org/): Learn how to create R Packages
    from the basics.
-   [R Programming for Data
    Science](https://bookdown.org/rdpeng/rprogdatascience/): Great
    overview of using R for Data Science, with more of a focus on the
    programming side of things
-   [rstats.wtf](https://rstats.wtf/): What They Forgot to Teach You 
    About R, a book on more advanced topics in R.
-   [Data Science](https://datasciencebook.ca/): A book on data science
    using R, with a focus on the tidyverse.
-   [R Packages](https://r-pkgs.org/): A book on how to create R
    packages. A very useful reference to use for when you want to create
    your own package.

## Quick references:

-   [RStudio
    cheatsheets](https://www.rstudio.com/resources/cheatsheets/):
    Multiple, high-quality cheatsheets you can print off to use as a
    handy reference.
-   [Tidyverse style guide](https://style.tidyverse.org/): To learn
    about how to write well-styled code in R.
-   [Tidyverse design philosophy of writing
    code](https://design.tidyverse.org/)

## Articles:

-   [Good enough practicies in scientific
    computing](https://doi.org/10.1371/journal.pcbi.1005510): An article
    listing and describing some practices to use when writing code.
-   [Best practices in scientific
    computing](https://doi.org/10.1371/journal.pbio.1001745).
-   Case study of reproducible methodds in Bioinformatics: [@Kim2018a].
-   [*Our path to better science in less time using open data science
    tools* article](https://www.nature.com/articles/s41559-017-0160)

## General sites:

-   [Organizing R Source
    Code](https://www.r-bloggers.com/r-best-practices-r-you-writing-the-r-way/).
-   [Hands-on tutorial for learning Git, in a web-based
    terminal](https://try.github.io/levels/1/challenges/1).
-   [Simpler, first-steps guide to using
    Git](https://rogerdudler.github.io/git-guide/).
-   [RStudio tutorial on using R
    Markdown](https://rmarkdown.rstudio.com/lesson-1.html).
-   [Markdown syntax
    guide](https://rmarkdown.rstudio.com/authoring_basics.html).
-   [Pandoc Markdown
    Manual](https://pandoc.org/MANUAL.html#pandocs-markdown) (R Markdown
    uses Pandoc).
-   [Adding citations in R
    Markdown](https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html).
-   [Case studies](https://www.practicereproducibleresearch.org/) and
    lessons for doing reproducibility

## Interactive sites or resources for hands-on learning:

-   [Interactive tutorials for using R, within
    R](https://swirlstats.com/).
-   [RStudio's Learning Primers](https://rstudio.cloud/learn/primers).

## Videos:

-   Video on using [Git in
    RStudio](https://rstudio.com/resources/webinars/managing-part-2-github-and-rstudio/).

## Getting help:

-   [StackOverflow for
    tidyr](https://stackoverflow.com/questions/tagged/tidyr).
-   [StackOverflow for
    dplyr](https://stackoverflow.com/questions/tagged/dplyr).
-   [StackOverflow for
    ggplot2](https://stackoverflow.com/questions/tagged/ggplot2?sort=frequent&pageSize=50).
-   Tip: Combine auto-completion with `::` to find new functions and
    documentation on the functions (e.g. try typing `base::` and then
    hitting Tab to show a list of all functions found in base R).
-   [Oh Shit Git!](https://ohshitgit.com/): A resource for dealing with
    Git issues.

<!-- ## Useful R packages -->

<!-- TODO: create csv and insert here? or create a script to make qmd to include here? -->

<!-- knitr::kable(r3::useful_packages_list, caption = "Useful and common packages to use in data analysis.") -->

## Teaching:

-   [Openscapes Champions Lesson
    Series](https://openscapes.github.io/series/): Learning materials
    for being a teacher.
-   [Framework for Open and Reproducible Research
    Training](https://forrt.org/clusters/): A great set of resources for
    learning about how and why to teach open and reproducible research.
-   Post: [Why beginners should
    teach](https://www.tatianamac.com/posts/why-beginners-should-teach)

## Examples:

These are some real world examples of how Git and GitHub are used in
health research, some of which also use R and incorporate
reproducibility.

-   Some research projects at Steno Aarhus using the UK Biobank data:
    -   [ukbAid](https://github.com/steno-aarhus/ukbAid): *An R package
        and documentation for streamlining the use of the UK Biobank
        data on the DNAnexux platform*
    -   [legliv](https://github.com/steno-aarhus/legliv): *The
        Association between Substitution of Red Meat with Legumes and
        Risk of Primary Liver Cancer in UK Biobank: A Cohort Study*
    -   [leha](https://github.com/steno-aarhus/leha): *Legumes as a
        substitute for red and processed meat, poultry, or fish, and the
        risk of non-alcoholic fatty liver disease in a large cohort*
-   Research projects at Steno Diabetes Center Aarhus:
    -   [LIVING
        Project](https://github.com/steno-aarhus/living-project): *A
        national evaluation of the patient education concept Lev Livet*
    -   [DP-Next](https://github.com/dp-next/): *Sustainable Type 2
        Diabetes Prevention for the 21st Century*
    -   [Seedcase Project](https://github.com/seedcase-project/): *A
        framework for open and scalable data: Software and training to
        bring data engineering to research*
    -   [ON-LiMiT](https://github.com/steno-aarhus/ON-LiMiT): *Remission
        of type 2 diabetes with diet and exercise*

These are, naturally, biased to project at Steno Aarhus since that is
where the lead instructor works. But if you have any examples to add
here, please let us know!
